config/routes.rb
Rails.application.routes.draw do
  # Defines the root path route ("/")
  devise_for :users, controllers: { registrations: "users/registrations" }
  # TOPページを top#index に設定
  root "top#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :books, only: [ :index ]
  resources :mangas, only: [ :index ]
  resources :movies, only: [ :index ]
  resources :user_productions, only: [ :create, :destroy ]
  get "/mangas/:id", to: "productions#show"
  get "/books/:id", to: "productions#show"
  get "/movies/:id", to: "productions#show"
  resources :productions, only: [ :show ] do
    resources :comments, only: [ :create ]
  end
  get "recommended_works", to: "works#recommended", as: "recommended_works"
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  get "my_list", to: "user_productions#index", as: :my_list
  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  get "/contact", to: "static_pages#contact"
  get "/terms",   to: "static_pages#terms"
  get "/privacy", to: "static_pages#privacy"
end

app/views/layouts/_flash.html.erb
<% flash.each do |key, message| %>
  <% css_class = case key.to_sym
    when :alert
      "bg-red-100 border border-red-400 text-red-700"
    when :notice
      "bg-green-100 border border-green-400 text-green-700"
    else
      "bg-gray-100 border border-gray-400 text-gray-700"
  end %>

  <div class="<%= css_class %> px-4 py-3 rounded mb-4 text-sm">
    <%= message %>
  </div>
<% end %>


app/views/layouts/_header.html.erb
<header class="p-4 [background-color:#97cdf3] text-white">
  <nav>
    <%= link_to "ホーム", root_path %>

    <% if current_user %>
      <!-- ログイン後のメニューバー -->
        <%= link_to "マイリスト", my_list_path, class: 'btn btn-primary' %>
        <%= link_to 'ログアウト', destroy_user_session_path, data: { turbo_method: :delete }, class: 'btn btn-danger' %>
        <%= link_to "おすすめの作品", recommended_works_path %>
    <% else %>
      <!-- 未ログイン時 -->
      <%= link_to 'ログイン', new_user_session_path, class: 'btn btn-primary' %>
      <%= link_to '新規登録', new_user_registration_path, class: 'btn btn-secondary' %>
    <% end %>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Myapp" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css" integrity="sha512-Evv84Mr4kqVGRNSgIGL/F/aIDqQb7xQ2vcrdIwxfjThSH8CSR7PBEakCr51Ck+w+/U6swU2Im1vVX0SVk9ABhg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <%= display_meta_tags(default_meta_tags) %> 
    </head>

  <body>
    <%= render 'layouts/header' %>

    <div id="flash">
      <%= render 'layouts/flash' %>
    </div>
  
      <%= yield %>
    <footer class="p-4 [background-color:#97cdf3] text-white" >
      <nav>
        <%= link_to 'お問い合わせ', contact_path, class: 'btn btn-primary' %> |
        <%= link_to '利用規約', terms_path, class: 'btn btn-primary' %> |
        <%= link_to 'プライバシーポリシー', privacy_path, class: 'btn btn-primary' %>
      </nav>
    </footer>
  </body>
</html>